### ISSUE TITLE
RK4 error estimation

### ISSUE THREAD

**Issue by devmotion** [JuliaDiffEq/OrdinaryDiffEq.jl#138]
The error estimation of RK4 is a bit confusing because of all aliases, but I think there might a problem in the in-place method. I just tried to update `fixed_timestep_integrators.jl`, and discovered lines
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/fixed_timestep_integrators.jl#L288
and
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/fixed_timestep_integrators.jl#L303
Isn't `p2` always zero since we defined `pprime2 = tmp` in line 288?

**Comment by devmotion** [comment]
And by the way, this (and many other methods, e.g. other fixed timestep methods or Rosenbrock methods) won't work for units since arrays such as `p2` at some points and contain rates but also unitless residuals.

**Comment by ChrisRackauckas** [comment]
Yeah, that looks like a bug. I was trying to get it without increasing the size of the cache, but it looks like it's necessary.

>And by the way, this (and many other methods, e.g. other fixed timestep methods or Rosenbrock methods) won't work for units since arrays such as p2 at some points and contain rates but also unitless residuals.

Yeah. For the Rosenbrock, units failed due to `\` last time I checked, so I haven't really cared about making the rest unit-compatible quite yet. For fixed timestep, I've just been on a method implementation rampage and was going to go back to clean up units later.

**Comment by devmotion** [comment]
> Yeah. For the Rosenbrock, units failed due to \ last time I checked, so I haven't really cared about making the rest unit-compatible quite yet. For fixed timestep, I've just been on a method implementation rampage and was going to go back to clean up units later.

Ah OK, so far I just added comments that it won't work to mark these methods since I wasn't sure whether some other parts are incompatible with units and whether it is worth changing the cache.

**Comment by ChrisRackauckas** [comment]
Should probably note that this isn't super high on the priority list because actually the collocation point that is used is supposed to be a measure of the maximum anyways. The second point Shampine argues should be added for safety, and the max is taken between the two. And indeed if there's a sharp change at the end of the interval that's a good idea. But as it stands, it's still actually correct and development can move forward with it. Though it would be trivial to fix when time allows.
