### ISSUE TITLE
Modify ODEProblem in-place?

### ISSUE THREAD

**Issue by sdwfrost** [JuliaDiffEq/OrdinaryDiffEq.jl#223]
Hi @ChrisRackauckas 

I have a PDMP problem in which I have to repeatedly solve an ODE with different parameter values. I can use ParameterisedFunctions to modify a function in-place, but then I have to create a new ODEProblem for every time step, which is killing the performance (7x cf using LSODA.jl). Is there a way that I can modify the ODEProblem in-place with different parameter values?

**Comment by ChrisRackauckas** [comment]
Why do you have to create a new ODEProblem for every timestep? That should never be necessary. 

http://docs.juliadiffeq.org/latest/analysis/parameterized_functions.html#The-AbstractParameterizedFunction-Interface-1

`set_param_values!(pf::AbstractParameterizedFunction,params)` sets new parameters to an arbitrary `ODEProblem`. If you used the macro to define the problem, you can always update the parameters via `f.a`, etc. Or if you used the `ParameterizedFunction` constructor, you can always update the parameters via `f.params .= ...`.

Creating a new `ODEProblem` is extremely cheap though since they are immutable structs. It would only be expensive if you are creating new arrays, which instead of doing that you can just modify the values of the internal arrays.

**Comment by sdwfrost** [comment]
I can (and do) change the parameter of the ParameterisedFunction, but I can't see how to update both the simulation times and the parameters efficiently to avoid creating a new ODEProblem. A working example of my problem is [here](https://gist.github.com/sdwfrost/5013a0f2439dd5da575302febf5636c8).

**Comment by ChrisRackauckas** [comment]
This is an algorithm-specific issue. In the `*DiffEq` algorithms you use a `DiscreteCallback` or the integrator interface for that. For `lsoda()`, you don't have step-by-step controls because we haven't put it into an integrator type (which is also why it doesn't do callbacks). That needs more development in the interface bindings for LSODA.jl. That's the missing X's in the compatibility chart ( http://docs.juliadiffeq.org/latest/basics/compatibility_chart.html ). 

The prerequisite for doing this is that the GC needs to be aware of the LSODA.jl's memory type so that way it can be GC'd without manually calling free (otherwise using this could cause memory leeks if the user isn't careful). Do you know if this has been setup yet? There was talk before that we may need to setup custom allocators to do this well with Sundials.jl, which is why development in this area stalled.

**Comment by sdwfrost** [comment]
I'm not bound to LSODA, but I want to avoid doing callbacks given that all I am simulating up to a specific time, rather than having some sort of complex condition on the dependent variables; the whole advantage of the uniformisation is that there isn't event detection. Is there no way to directly access ODEproblem to reset the parameters and simulation times?

**Comment by ChrisRackauckas** [comment]
>I want to avoid doing callbacks given that all I am simulating up to a specific time, rather than having some sort of complex condition on the dependent variables; the whole advantage of the uniformisation is that there isn't event detection

But you are doing event detection in your example. The other method is just solving until `t+s`. A `DiscreteCallback` is the exact some thing. You just do something like:

http://docs.juliadiffeq.org/latest/features/diffeq_arrays.html#Example:-A-Control-Problem-1

where you can have an array (or a `Ref`) which you subsequently add future times to stop at, and do you effect. Notice that a `DiscreteCallback` is not "event detection" like a `ContinuousCallback`.  A `DiscreteCallback` simply checks some boolean at the end of a step and then applies the affect, so it's a super cheap operation (in fact, if it's usually false then branch detection kicks in and it's free). Only `ContinuousCallback`s to interpolation + rootfinding: that's expensive. But not a `DiscreteCallback`.

But if you don't want to use a `DiscreteCallback` for this, just use the integrator interface.

http://docs.juliadiffeq.org/latest/basics/integrator.html#Initialization-and-Stepping-1

Basically instead of using `sol = solve(prob,alg,...)`, you do `integrator = init(prob,alg,...)`, and then you can `step!(integrator)` to do one step at a time and apply changes between steps whenever you want. This is similar to how you're using LSODA (and this is the integrator I would like to build for LSODA as well, but need proper GC for this).

>Is there no way to directly access ODEproblem to reset the parameters and simulation times?

Either way, you get access to the integrator from callbacks or directly using the integrator interface for stepping. From there, parameters are stored in `integrator.f` and thus you just change them. The simulation just runs until a `tstop`, so you just use `add_tstop!(i::DEIntegrator,t)` to force stopping at that `t` (you can remove tstops too). We should probably get some tutorials up showing this step-by-step interface more, but here's some tests that show some of what it does:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/test/iterator_tests.jl

>(the default solver involves twice as many allocations and takes twice as long in my toy example).

I would give `BS3()`, `Vern7()`, and `Vern9()` a try. Either higher or lower order might be better here, but I don't know a priori which it would be. LSODA is probably sticking to low order due to the discontinuities, or maybe the tolerance is low enough that high order matters. It may also be semi-stiff which then LSODA gets right (because it switches between implicit and explicit methods), so a stiff solver like `Rosenbrock23()` might also be worth a try. Or maybe LSODA is just good here. But the default is decent on most problems but rarely the best since it's so middle of the road.

I'm travelling so I don't have time to give more details, but now that I see that an in-depth example for the integrator interface is missing I put that on the list for when I get back. Hopefully this is decipherable or if not I can write up some examples soon.

**Comment by ChrisRackauckas** [comment]
This is more of documentation / conversation, so I'm closing. Feel free to chat more if you need more help here. Hopefully we can get the integrator interface up and running on Sundials et. al. now that we have Jacobian passing!

**Comment by ChrisRackauckas** [comment]
Did you ever get this solved? We now have the callback interface on Sundials.jl which should do it.

**Comment by ChrisRackauckas** [comment]
BTW, can you share the problem which is not doing well in the DiffEq methods? I would like to benchmark it some.
