### ISSUE TITLE
Allocating when resizing Jacobians

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#29]
The way that Jacobians are currently resized they actually cause a reallocation every time as pointed out by @ScottPJones. A workaround is to create a wrapper type with a vector and indexing like a matrix (row = mod, column = integer division), and define the appropriate dispatches on this (and make it an `AbstractMatrix`). This will then cause less allocations when resizing since it will allow it to do the normal `resize!` behavior.

**Comment by ScottPJones** [comment]
I think there may be ways you can avoid the (slow) integer division, and the div/mod are only needed when going from a linear index to a matrix index anyway (unless you restrict dimensions to powers of 2 [which I did with my sparse bits code for speed, I precalculated shifts and masks]), otherwise it's just a muladd.

**Comment by ChrisRackauckas** [comment]
Need to test Tim Holy's solution:

http://stackoverflow.com/questions/41781621/resizing-a-matrix

**Comment by ChrisRackauckas** [comment]
It seems like that allocates too. Sounds like this is impossible.
