### ISSUE TITLE
solve seems to be ignoring dtmin

### ISSUE THREAD

**Issue by ronisbr** [JuliaDiffEq/OrdinaryDiffEq.jl#31]
Hi @ChrisRackauckas,

I am trying to use this package with a inferior limit for the `dt`. However, it seems that this limits is not being used. Consider, please, the following code:

https://gist.github.com/ronisbr/99cc40134d9a5551738e22622b47c3f4

which is the same as the last one you sent to me, but with `display(t)` at the dynamic function.

I set `dtmin = 0.5`, but I am seeing at the output the following:

```
0.0
0.02
0.0
0.02297442656090463
0.034461639841356945
0.09189770624361852
0.10210856249290945
0.11487213280452314
0.11487213280452314
0.11487213280452314
0.28244333504772334
0.3662289361693234
0.7851569417773239
0.8596330316631905
0.952728144020524
0.952728144020524
0.952728144020524
1.1731621821946665
1.283379201281738
1.8344642967170945
1.9324349803500467
2.054898334891237
2.054898334891237
2.054898334891237
2.3309932248453284
2.4690406698223737
3.1592778947076017
3.281986734687198
3.435372784661693
3.435372784661693
3.435372784661693
3.735038328945375
3.8848711010872155
4.634034961796419
4.767219648144723
4.9337005060801005
4.9337005060801005
4.9337005060801005
4.946960404864081
4.95359035425607
4.98674010121602
4.992633389564456
5.0
5.0
5.0
5.132598987839799
5.198898481759699
5.530395951359196
5.589328834843552
5.662994939198995
5.662994939198995
5.662994939198995
5.868122275443408
5.970685943565614
6.483504284176646
6.574671989174162
6.688631620421058
6.688631620421058
6.688631620421058
6.950905296336846
7.08204213429474
7.737726324084211
7.854292402269007
8.0
8.0
8.0
8.306606564893508
8.459909847340262
9.226426259574033
9.362695843971148
9.53303282446754
9.53303282446754
9.53303282446754
9.626426259574032
9.673122977127278
9.906606564893508
9.948114758274171
10.0
10.0
```

It seems that the time step is sometimes much lower than the `0.5`. Am I doing something wrong?

**Comment by ronisbr** [comment]
In my simulator, sometimes I saw this:

```
239.8342353738439
239.84726235761903
239.91239727649472
239.92397681762816
239.93845124404498
239.93845124404498
239.93845124404498
239.95076099523598
239.9569158708315
239.987690248809
239.99316124933833
240.0
240.0
239.9487514746136
239.95390158989792
239.9796521663195
239.98423004657224
239.98995239688813
...
```

What can be causing so many calls to the dynamic function?

**Comment by ChrisRackauckas** [comment]
Hmm, I'll take a look into this. I realize that the issue is because when `dtmin` is set, it'll go to the minimum, but then not be able to satisfy the error, and so weird stuff begins to happen. What I need to do is force it to accept steps if `dt==dtmin`.

>What can be causing so many calls to the dynamic function?

Is the problem stiff? I'll take a look into what happens when time gets large. It's likely because the numbers grow, so the errors grow, and so the absolute tolerance is hard to reach.

**Comment by ronisbr** [comment]
Hi @ChrisRackauckas,

I figured out the problem with my model. Sometimes there are discontinuities generated by many factors like shadows, change in direction of reaction wheels, etc. that increase a lot the error. In these cases, the algorithm tries to match the absolute error but ignores the `dtmin`, which leads to my problem. My dynamic function is very slow, in these cases, 1s in the simulation takes 5s. This will not be good since I want to do a Monte Carlo simulation to analyze the impact of the initial state. I don't mind the error generated by the `dtmin`, I am more worried with the execution time.

Thanks!
Ronan

**Comment by ChrisRackauckas** [comment]
One way to make things quicker is to use a standard array and parameters on the function. This would not save the values of the discrete variables at the given times though, if that's required. I can re-write the example to show how to do that if you want.

>Sometimes there are discontinuities generated by many factors like shadows, change in direction of reaction wheels, etc. that increase a lot the error.

Are you handling the discontinuities in a callback? If so, there should be no error associated with discontinuities. If there are discontinuities outside of callbacks, then yes I'd expect errors to be high.

>My dynamic function is very slow, in these cases, 1s in the simulation takes 5s. 

Are you saying that your data function `f` is slow? If that's the case, it'll take some profiling to determine the best method here. If the problem is stiff, you'll want to use a stiff method (which will increase the timesteps). If the timesteps are being limited by the discrete events, then you'll want to stick with a nonstiff solver for sure. If you want to privately share the code for profiling, let me know and I'll help you out.

>I want to do a Monte Carlo simulation to analyze the impact of the initial state.

Have you seen this? http://docs.juliadiffeq.org/latest/features/monte_carlo.html

**Comment by ronisbr** [comment]
> Are you handling the discontinuities in a callback? If so, there should be no error associated with discontinuities. If there are discontinuities outside of callbacks, then yes I'd expect errors to be high.

The discontinuities I mentioned cannot be handled in callbacks, because it depends on many dynamic factor like: satellite attitude, Sun position, Solar Array position, etc. That's why the errors grow up and I need one way to avoid a very small sampling step. Is there any way to accomplish this now? 

> Are you saying that your data function f is slow? If that's the case, it'll take some profiling to determine the best method here. If the problem is stiff, you'll want to use a stiff method (which will increase the timesteps). If the timesteps are being limited by the discrete events, then you'll want to stick with a nonstiff solver for sure. If you want to privately share the code for profiling, let me know and I'll help you out.

It is **very** slow. I compute many things inside this function: orbit propagation, attitude propagation, reaction wheel simulations, earth magnetic field, many sensors output, etc. etc. etc. I am using `BS3()`, because `Tsit5()` and `DP5()` became veeeery slow because I can't set a `dtmin` for the entire simulation.

> Have you seen this? http://docs.juliadiffeq.org/latest/features/monte_carlo.html

No! This is awesome, will save me a lot of time :) Thanks!

**Comment by ChrisRackauckas** [comment]
>The discontinuities I mentioned cannot be handled in callbacks, because it depends on many dynamic factor like: satellite attitude, Sun position, Solar Array position, etc. That's why the errors grow up and I need one way to avoid a very small sampling step. Is there any way to accomplish this now?

See the `ContinuousCallback`. This example shows how to handle a discontinuity:

http://docs.juliadiffeq.org/latest/features/callback_functions.html#Example-1:-Bouncing-Ball-1

**Comment by ronisbr** [comment]
@ChrisRackauckas,

Well, now I know what is causing my problem:

- The reaction wheels simulation has a static drag that depends on the direction of the spinning.
- When the velocity is almost 0, then this static drag starts to give problems to the simulation, because it itself cannot change the spinning direction. This happens if I code this discontinuity with a callback or if I code inside the dynamic function.
- I decided to do a ugly workaround that solved the problem at least for now. When the velocity is slow enough, I changed the static drag from `-c*sign(w)` to `-c*w`. This improved a lot the simulation until I could use `dtmin` to force a minimum integration step.

I was looking at the code to see if I can help with this issue. Do you have any tips?

**Comment by ronisbr** [comment]
Would it be enough to modify this function:

```julia
@inline function loopfooter!(integrator)
```

I was thinking in algorithm like that:

* If `dt < dtmin`, then `dt = dtmin` and `apply_step = true`.

Any problems with that?

**Comment by ChrisRackauckas** [comment]
>I was looking at the code to see if I can help with this issue. Do you have any tips?

No. It shouldn't be difficult to actually do, but it's conceptually difficult to describe. Usually,  

>This improved a lot the simulation until I can use dtmin to force a minimum integration step.

this is not the behavior for this reason. The behavior from `dtmin` in every other differential equation package is to throw a warning and exit whtn `dt<=dtmin` because otherwise you're not actually guaranteeing the tolerance, and the advice to the user is usually to make the tolerance higher. 

>Would it be enough to modify this function

Maybe, maybe you can just `integrator.accept_step = true` when at `dtmin`.  It would be this line:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/integrator_utils.jl#L145

**Comment by ronisbr** [comment]
No, I see it will not work. `loopfooter` is called after the solution. So I think I will have to modify also:

```julia
@inline function loopheader!(integrator)
```

**Comment by ChrisRackauckas** [comment]
>No, I see it will not work. loopfooter is called after the solution. So I think I will have to modify also:

The `loopheader!` should just be making its decisions based on `accept_step`, so the modification in the footer should work. I'd test that thoroughly though.

**Comment by ChrisRackauckas** [comment]
>When the velocity is almost 0, then this static drag starts to give problems to the simulation, because it itself cannot change the spinning direction. This happens if I code this discontinuity with a callback or if I code inside the dynamic function.

Could you describe that more? I am wondering if there's a different solution that is based on solving this model issue.

**Comment by ronisbr** [comment]
Of course:

The static drag torque of a rection wheel (all motors indeed) can be modeled by:

```
T_sd = -c*sing(w)
```

in which `c` is the Coulomb friction and `w` is the angular velocity of the wheel. Hence, the model can be written as:

```
T = T_c + T_sd - k*w
```

where `T_c` is the commanded torque (related to the voltage applied to the wheel), `k` is a wheel parameter describing the viscous drag torque, and `T` is the net torque on the wheel.

 The problem arises when `w` is very low. In this case, depending on the sampling step, it changes the direction of the wheel rotation, which is impossible.

**Comment by ronisbr** [comment]
I was wondering, if set `dt = dtmin` is not the expected behavior on the solver, what if we create an option like `force_dtmin`?

**Comment by ChrisRackauckas** [comment]
>I was wondering, if set dt = dtmin is not the expected behavior on the solver, what if we create an option like force_dtmin?

Yeah, that's what I was thinking. A new boolean in the integrator `force_dtmin` and if that's true, set `accept_step` true on the line I pointed to when `dt==dtmin`. The fact that it currently is able to go below `dtmin` is worrysome because I would've thought that up here:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/integrator_utils.jl#L244

would've already made sure the timestep would've never gotten below `dtmin`, so it may take a little bit more to find out how to really fix the timestep since the fact that it can go lower is a bug.

**Comment by ronisbr** [comment]
Well, let's see if I am understanding those things:

* `calc_dt_propose!` is called in `loopfooter!` if the step is accepted.
* Suppose that the step is not accepted and `dt = dtmin`.
* I think that, in this case, this will be called https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/integrator_utils.jl#L15 and will reduce `dt` violating `dtmin` until the step is accepted and `calc_dt_propose!` is called inside `loopfooter!`.

Am I right?

**Comment by ChrisRackauckas** [comment]
Yes, so the way around it is to force `accept_step==true` so it takes this branch instead

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/integrator_utils.jl#L10

**Comment by ronisbr** [comment]
What do you think to change the line you mentioned in `loopfooter!` to:

```julia
 integrator.accept_step = (!integrator.isout && ( integrator.EEst <= 1.0 || integrator.dt == integrator.opts.dtmin ) )
```

**Comment by ChrisRackauckas** [comment]
Yes, that's what I would try.

**Comment by ronisbr** [comment]
Ok! I does not have access to my simulator right now. Tomorrow at my institute I will do this and, if everything seems fine I will make a PR :)

Thanks @ChrisRackauckas one more time!

**Comment by ChrisRackauckas** [comment]
Let me know if you need anything more.

**Comment by ronisbr** [comment]
One last question: `dt` can be negative right? Should I use `abs`?

**Comment by ChrisRackauckas** [comment]
>One last question: dt can be negative right? Should I use abs?

Yes, you could be going in the reverse direction so you need to check size using `abs`

**Comment by ronisbr** [comment]
Hi @ChrisRackauckas,

One question, when I set `dtmin > 1.0` at the bouncing ball example, one of the events is being discarded:

![bouncing_ball_problem](https://cloud.githubusercontent.com/assets/1068295/22406899/ff263ba6-e642-11e6-9fc9-54b741b06ac2.png)

This is happening with `master`. Here is the code I am using:

https://gist.github.com/ronisbr/c4b3169dfd44d231a9f5f1866538e242

Is it expected?

**Comment by ChrisRackauckas** [comment]
>Is it expected?

No, and now that I think about it setting up `dtmin` to work well with events like this may be tricky. It'll need a diagnosis of exactly why it failed to detect the event.

**Comment by ronisbr** [comment]
Yeah, that's what I thought. I think it will be much more complicated than I was expecting.

**Comment by ronisbr** [comment]
I think I am almost understanding the problem. When I executed the code without `saveat`, look what points it saved:

![bouncing_ball_no_saveat](https://cloud.githubusercontent.com/assets/1068295/22409530/11c81c6e-e672-11e6-96d1-ae8c90f5816b.png)

Does it can explain something?

Furthermore, if I add `abstol=1e-4`, then I get:

![bouncing_ball_abstol](https://cloud.githubusercontent.com/assets/1068295/22409555/5c28169c-e672-11e6-9392-7891a588cc6a.png)

So, maybe, the problem isn't at the algorithm itself, but in the configurations. Like, this problem will not work if I set `dtmin>1.0` and use the default `abstol`. What do you think?

**Comment by ronisbr** [comment]
Nevermind, the problem occurs only if I set `dtmin = 2.0`. With `dtmin = 4.0` for example it works...

**Comment by ChrisRackauckas** [comment]
It needs to look at exactly why it's hitting the points it is when `dtmin` is set. That's hard to tell from these plots.

**Comment by ronisbr** [comment]
Do you remember when you first propose this new callback interface it started to ignore my discrete callbacks? Then you proposed the continuous and discrete callbacks? Is there any possibility that this "bug" is affecting continuous callbacks when I set `dtmin = 2.0` in this example?

**Comment by ronisbr** [comment]
Aha! It really seems to be something like it. I can change the behavior by avoiding a very big step. In this example, if I set `dtmin = 2.0` and `dtmax <= 9.0` then the event is not discarded. Look at the sampling steps:

```
dtmin = 2.0
  0.0        
  0.000101935
  2.0001     
  3.19275    
  3.19275    
 15.0

dtmin = 2.1
  0.0        
  0.000101935
  2.1001     
  3.19275    
  3.19275    
  9.57826    --> Time of the second event
  9.57826    
 15.0

dtmin = 2.0 and dtmax = 9.0
  0.0        
  0.000101935
  2.0001     
  3.19275    
  3.19275    
  9.57826    
  9.57826    
 15.0   

dtmin = 2.0 and dtmax = 10.0
  0.0        
  0.000101935
  2.0001     
  3.19275    
  3.19275    
  3.19275    
  3.19275    
 13.1928     
 15.0 
```

**Comment by ChrisRackauckas** [comment]
>Is there any possibility that this "bug" is affecting continuous callbacks when I set dtmin = 2.0 in this example?

If the `dt` is really high, it can have trouble finding events because it has to  find a root in the condition (a crossing over zero). Maybe when you have a really large timestep, for your problem you need to increase the number of interpolation points to check at. Or maybe the callback tolerances need to be adjusted. It's hard to know without actually looking at it in detail. I'll look at that bouncing ball a little later. With what changes to the solver is this being run?

**Comment by ronisbr** [comment]
I don't see this problem at my simulator. I only saw it at the bouncing ball example when I was testing the proposed modifications to handle the original problem of this thread. All the results I posted here were executed using the `master` branch of this package without any modifications.

**Comment by ChrisRackauckas** [comment]
I see. I'll take a look into this tonight to find out how `dtmin` is affecting it. My guess is that when it's upped you're going to need to increase the `interp_points`.

**Comment by ChrisRackauckas** [comment]
pinging @ccontrer since you've been helpful with these event handling issues.

The problem is clearly shown by looking at the following:

```
println(sol.t)
[0.0,0.000101935,2.0001,3.19275,3.19275,15.0]
println(sol[end-1])
[7.10543e-15,31.3209]
```

Let me explain what this means. The first event happens at `t=3.19` where the discontinuity is correctly handled. Then, what's incorrect and needs to be fixed separately, is that the solver steps to `t=15` for some reason. This is the `dtmin` issue.

However, now this exposes a weird event handling issue. Since `sol[end-1]` had a `condition` which was `7e-15 < cb.abstol`, events in that next timestep are ignored. But this means that the tolerance handling will never allow events one after another.

Notice that if you change the callback to:

```
cb = ContinuousCallback(condition,apply_event!,rootfind,save_positions,abstol=1e-16)
```

then it works. Maybe this means we should drop the tolerance idea? I can't think of a good way to make the tolerances not have this problem.

**Comment by ChrisRackauckas** [comment]
BTW, is there a reason you didn't use the in-place form for `f`?

```julia
function f(t,u,du)
    du[1] = u[2]
    du[2] = -9.81
end
```

**Comment by ronisbr** [comment]
> Maybe this means we should drop the tolerance idea? I can't think of a good way to make the tolerances not have this problem, and the prevfloat(prevfloat( domain fix should handle most cases the tolerances were need for before. Another thing that can be done is that the default tolerance can be set below machine epsilon, so that by default it isn't event-event blocking, but still gives the user the choice to enable it since there are some cases you may need to stop "double eventing" (example: "buncing ball" where the velocity doesn't actually go positive. It will back up to before the event each time there's an event, so I don't think that the ball could ever actually go negative since it will be stuck hitting the same event repeatedly). I don't think there exist a set of options that will handle every case in a good way automatically, which is why instead we probably should just be looking for decent defaults, and expand the tutorials for how to deal with issues.

This is a very good approach. It will be difficult (impossible) to deal with everything automatically. Maybe set the tolerance equal to the machine epsilon will work.

> BTW, is there a reason you didn't use the in-place form for f?

Yes! I used to be a C/C++ & Matlab programmer :) I am still trying to get used to the julia way of doing things. What would be a in-place form for f?

**Comment by ChrisRackauckas** [comment]
>What would be a in-place form for f?

I showed it above:

```julia
function f(t,u,du)
    du[1] = u[2]
    du[2] = -9.81
end
```

it writes directly to the `du` cache instead of making a new array. It'll be a lot faster for large arrays.

**Comment by ChrisRackauckas** [comment]
Here's a simple condition that breaks if the tolerance is zero:

```julia
condition= function (t,u,integrator) # Event when event_f(t,u,k) == 0
  t - 2.95
end
```

Since it always stops you off the floating point number just before the event, if the tolerance isn't high enough then it will keep hitting the same event. I need to think of something much smarter.

**Comment by ChrisRackauckas** [comment]
Right after posting that I came up with a solution that will solve these problems. It's in this commit:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/d31e6bca9daf9fa386c57818f7e603e1d67eae2e

Essentially, the problem was that it was always checking if there was a sign change between the previous timepoint and next "timepoints" where the next means all of the interpolated values as well. So it would check if the left is of a different sign vs 10 evenly spaced points. This sounds nice... but...

If the left is below the tolerance from zero, its sign was set to zero. This was to solve the `condition` of `t-2.95` problem of above which just causes events to continue to happen at the same point. But this meant nothing could have a different sign from the left because it was checked by multiplying the two signs and seeing if it's less than zero!

The real solution is, if the left endpoint is essentially zero, discard it and look for events just to the right of the left. What I mean is, if we say that the timepoints are [1,2,3,4,5], (this would mean there are 5 interp points (by linspace), 1 is the previous value, 5 is the value we stepped to, and 2,3,4 are interpolated values), then we can discard `1` and look for events on [2,3,4,5]. Thus we can keep a high enough tolerance to stop repeat events at `1`, but we will still find events in the next timestep if they are after `2`.

Using the default `interp_points=10`, this means that as long as the event is not in the first 1/8 of the interval, it will find it. Better resolution is gained by increasing `interp_points`. But that's always the case: if the function is oscillatory, then rootfinding there requires increasing the `interp_points` as well. So this makes it much easier: `interp_points` is set at a reasonable default for it's ability to find reasonably spaced events on reasonably oscillatory problems (at least 1 negative value and 1 positive value must occur in one of the 9 or 10 evenly spaced points in the interval), but if you need better resolution, increasing `interp_points` will solve the problem. That makes it easy to document as well.

This is on master. I moved `rootfind` and `save_positions` to be keyword arguments since the most standard case is `true` and `(true,true)`, so I thought it may as well be a little more automatic. My tests show that this new strategy works really well. I'll see if I can tag versions soon: I just implemented event finding in SDEs.

**Comment by ronisbr** [comment]
@ChrisRackauckas very nice work! Congratz!

I had just one problem. Using exactly the same example (bouncing ball), the problem persists if I use `dtmin = 2.0` and `dtmax = 10.0`. If I set only `dtmin = 2.0` or `dtmax = 10.0`, then everything is fine.

The behavior is very strange. For example, `dtmin = 2.0, dtmax = 11.0` also has problems to detect the second event, but `dtmin = 2.0, dtmax = 13.0` detects everything fine. I would have not expected that the set of the maximum time step allowed would change the detection behavior so much.

**Comment by ChrisRackauckas** [comment]
>I had just one problem. Using exactly the same example (bouncing ball), the problem persists if I use dtmin = 2.0 and dtmax = 10.0. If I set only dtmin = 2.0 or dtmax = 10.0, then everything is fine.
The behavior is very strange. For example, dtmin = 2.0, dtmax = 11.0 also has problems to detect the second event, but dtmin = 2.0, dtmax = 13.0 detects everything fine. I would have not expected that setting the maximum time step allowed would change the detection behavior so much.

Is this using master? This still doesn't address whatever `dtmin` is doing.

**Comment by ronisbr** [comment]
Yeah this is using master. After your patch, the event is being identified if I set `dtmin=2.0`. This was not happening before the patch. Now, I can find combinations of `dtmin` and `dtmax` that yield to the event being discarded.

**Comment by ChrisRackauckas** [comment]
```
println(sol.t)
[0.0,0.000101935,2.0001,3.19275,3.19275,9.57826,9.57826,15.0]
```

It was triggering the first event 3 times, and then continuing. This means that the rootfinding didn't put it within `1e-14` of the event. Now that using the tolerances is much safer, I upped the default to `1e-12` and that fixes the problem.

**Comment by ronisbr** [comment]
Was this result obtained with `dtmin=2.0, dtmax=3.0`?

**Comment by ChrisRackauckas** [comment]
`dtmin=2.0` and `dtmax=10.0`.

**Comment by ronisbr** [comment]
I mean `dtmax=10.0`? (Can't edit on mobile...)

**Comment by ChrisRackauckas** [comment]
FWIW `dtmax=3.0` works too.

**Comment by ronisbr** [comment]
OK! Thanks one more time! Excellent result. Now I can go back to the proposed fix for the original problem.

**Comment by ChrisRackauckas** [comment]
I am working on the `dtmin` thing right now. What was the name for the flag doing to be (for switching behavior between erroring and just continuing)?

**Comment by ronisbr** [comment]
Maybe `force_dtmin`?

**Comment by ChrisRackauckas** [comment]
yes, that was the good one. Thanks.

**Comment by ronisbr** [comment]
I was coding something like that:

If `dt <= dtmin` and `force_dtmin` then accept the step. In this case, if error tolerance is not met, print a warning telling to increase `dtmin` if verbose is true.

What do you think?

**Comment by ChrisRackauckas** [comment]
The one violation to `dtmin` which is allowed is if the distance to the next `tstops` point is small than `dtmin`. It will always step to each `tstops` point.

**Comment by ChrisRackauckas** [comment]
And events. It will backup below `dtmin` if there was an event.

**Comment by ronisbr** [comment]
That is indeed very very important.

**Comment by ChrisRackauckas** [comment]
The described behavior is implemented on master and I'll be doing a release this week.
