### ISSUE TITLE
Wrong array access for interpolation out of integration limits

### ISSUE THREAD

**Issue by fedxa** [JuliaDiffEq/OrdinaryDiffEq.jl#36]
The current master fails if the solution is attempted to be calculated beyond the end of the integration:

```julia
tprob = ODEProblem((t,x)->x, 1.0, (0.0,1.0))
tsol = solve(tprob, Euler(), dt=0.1)
tsol(2)
```

In the current master version this actually leads to a segfalut.  If you remove all the "@inbounds" macros in `OrdinaryDiffEq/src/dense/generic_dense.jl` you will get

> ERROR: BoundsError: attempt to access 12-element Array{Int64,1} at index [13]
>  in ode_interpolation at /home/fedor/.julia/v0.5/OrdinaryDiffEq/src/dense/generic_dense.jl:222 [inlined]
> 

out of this code

**Comment by ChrisRackauckas** [comment]
It's expected that it won't work, but it's not good that it segfaults (because of trying to access past the array's final value). I'll have to add a check for if the time is past the final time, and I'll make that throw a better error.

If you need extrapolations, you can get that through the integrator interface.

**Comment by ChrisRackauckas** [comment]
Fixed by https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/commit/69f94eee88faf4341a6c6bd525cd426b31e4abf0

**Comment by fedxa** [comment]
Exactlylike this -- I don't really need this to work, but segaults make me
restart the session
