### ISSUE TITLE
Strong Stability Presurving RK Methods

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#39]
This was brought up by @ranocha. These methods are good for discretizations of hyperbolic PDEs.

http://epubs.siam.org/doi/abs/10.1137/07070485X
http://www.worldscientific.com/worldscibooks/10.1142/7498
http://www.cfm.brown.edu/people/sg/SSPpage/sspsite/erk_nl.html

The RK methods can be implemented like any other RK method. However, the higher order RK methods can use something called a `limiter`. Since this is defined by the parts of the `ODEProblem`, it can be a toggle in the algorithm. Example:

```julia
SSPRK3(limiter=:highly_conservative)
```

These will need a little bit of extra documentation for that, but that should be fine. The limiter only needs to do things in the `perform_step` method, so nothing about the implementation needs to be specific. The RK method without the limiters should be added first, and tested, and then the limiters should be added.

A side note for making this simpler to work with. The symbol should be saved as a type parameter in the algorithm. A helper function should probably be added in alg_utils.jl that looks kind of like this:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/alg_utils.jl#L22

which is used to grab the symbol from the type information of the symbol. This will allow the branches for/not-for using the limiter to be compile-time information and compile away depending on the algorithm choice. 

From what I can see, there are not specific dense outputs for these, and so a simple Hermite polynomial should be sufficient. These do not have an error estimator from what I can see, which means they may not be able to be adaptive.

**Comment by ranocha** [comment]
I have implemented a first version of the two-stage, second-order SSP Runge-Kutta method in #40. Before I continue implementing methods, I would like to know whether these changes are acceptable.

**Comment by ChrisRackauckas** [comment]
I found these materials on adding dense output:

http://download.springer.com/static/pdf/258/art%253A10.1007%252Fs10915-016-0331-5.pdf?originUrl=http%3A%2F%2Flink.springer.com%2Farticle%2F10.1007%2Fs10915-016-0331-5&token2=exp=1497843999~acl=%2Fstatic%2Fpdf%2F258%2Fart%25253A10.1007%25252Fs10915-016-0331-5.pdf%3ForiginUrl%3Dhttp%253A%252F%252Flink.springer.com%252Farticle%252F10.1007%252Fs10915-016-0331-5*~hmac=e6b6ff529639fc409ad2705e1db08064897653efdf2afd8f5bba94702fcd13e4

Right now they all default to 3rd order Hermite, which does not satisfy the SSP requirement. Adding this dense output wouldn't be difficult and would give them SSP interpolants.

Are there any with adaptive timestepping though?

**Comment by ranocha** [comment]
I'll have a look at the paper at the end of this week.

I don't know whether there are adaptive SSP methods. For hyperbolic PDEs, the usual approach is to set some CFL number and use the resulting allowed time step. Thus, the time step is restricted by the stability condition and the corresponding accuracy is (assumed to be) acceptable.

**Comment by ranocha** [comment]
Concerning the limiters: The choice of the limiter is highly dependent on the actual semidiscretisation. Thus, I would like to call something like `stage_limiter` after each Euler stage of the method and a `step_limiter` after the full time step. Default implementations of these functions would do nothing an the user can implement specialised methods for his own types.

**Comment by ranocha** [comment]
There is an embedded SSPRK method with four stages and orders 3 and 2, described in section 6.3 in the book of Gottlieb, Ketcheson and Shu (2011). I will implement this one, together with SSP dense output.

**Comment by ChrisRackauckas** [comment]
The new method needs a citation and the docs need an update.

**Comment by ranocha** [comment]
JuliaDiffEq/juliadiffeq.github.io#7
JuliaDiffEq/DiffEqDocs.jl#30

**Comment by ChrisRackauckas** [comment]
https://scicomp.stackexchange.com/questions/27194/adaptive-timestepping-for-stong-stability-presurving-ssp-runge-kutta-methods

Looks like more error estimators may come soon. I emailed @ketch to see if I could get those coefficients.

We may want to add a callback to the callback library which handles the `dtFE` problem though. I am not entirely familiar with this, but it would be easy to make a `DiscreteCallback` change the `maxdt`. From the post, it sounds like a user should at least know the function they would want to have for `dtFE`, so we can make a callback that adapts `maxdt` according to a function.

**Comment by ranocha** [comment]
I'll have a look at callbacks, probably at the end of this week. As David Ketcheson wrote, it is more usual to set some time step limit (as `dtFE`)  due to stability constraints (CFL condition). Thus, I will see how this can be implemented at first.

**Comment by ranocha** [comment]
I'll be away from any computer for the next few weeks. After that, I'll write down some simple discretisations for hyperbolic PDEs in another repo and implement callbacks for the CFL condition.

**Comment by ChrisRackauckas** [comment]
Sounds great. As always, take your time. Nice work. I'll definitely give you a bunch of shoutouts when we start talking about the PDE story!

**Comment by ChrisRackauckas** [comment]
New resource:

https://www.brown.edu/research/projects/scientific-computing/sites/brown.edu.research.projects.scientific-computing/files/uploads/Strong%20Stability-Preserving%20High-Order%20Time%20Discretization%20Methods.pdf

I think we can just document that the user should set `dtmax = dtFE`. Does that sound good? Does `dtFE` change throughout the problem?

Is there a place I can read more on these `limiter`s? I'm not entirely sure what they are supposed to do.

**Comment by ketch** [comment]
`dtFE` does change in time for nonlinear problems.  The first part of Section 2.1 of this paper might help explain things (the publisher screwed up the section title):

http://epubs.siam.org/doi/pdf/10.1137/15M101717X

There's a freely-accessible copy on arxiv.org too.

**Comment by ChrisRackauckas** [comment]
I see. So the limiter is `dtFE = dtFE(t,u)` a function which is dependent on the problem that limits the stepsize? Could we assume that the user will know this to an approximation, or can it be off by a proportion constant? The statement "hFE is proportional to the CFL number": is this proportion constant `<1` or will users supply the CFL number and end up with instability?

As for implementation, we can make a `DiscreteCallback` that takes in such a function and changes `dtmax` at each timestep using the current `t` and `u`. More aggressively in the fixed timestep case, there can be an option so that the fixed timestep methods could have it change `dtcache`, which would make each step be `dt=dtFE` and thus equivalent to Remark 2. I think the callback should probably have a safety factor, so actually it's all like `dt < fac*dtFE` where the default `fac=0.9` sounds good (matches standard adaptivity safety factors). This callback can be added to the callback library.

**Comment by ranocha** [comment]
Finally, I have access to the internet again.

Step sizes: `dtFE` depends also on the semidiscretisation, i.e. on the time derivative function `f`. Thus, a discrete callback should be good.

Limiters: They are not used to limit the step size. Instead, they are some kind of callback that is applied several times during each time step of the `SSPRK` method, ensuring the validity of the solution `u`. Considering the discretisation of some density that cannot be negative, the limiters would ensure this non-negativity of the numerical solution, since most semidiscretisation cannot enforce such non-negativity without further modifications.

**Comment by ChrisRackauckas** [comment]
>The proportion constant depends on the SSP coefficient, i.e. on the time integrator itself.

Should we add SSP coefficients as algorithm traits that can be queried when needed?

For the stepsize limiter, I made something for the callback library:

http://docs.juliadiffeq.org/latest/features/callback_library.html#Stepsize-Limiters-1

It's very basic and we could add usage of the SSP coefficient. Is there a resource which gives this relation?

Concerning limiters: I assume they will be needed in the implicit SSP methods as well? The issue for that is
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/issues/97 , and there's already SSPSDIRK2 implemented. I'll follow your lead here since I'm still not quite sure what these are.

**Comment by ranocha** [comment]
I've added the SSP coefficients of the explicit SSP methods in #169.

### Stepsize limiter

The `StepsizeLimiter` in the callback library looks good. There are at least two use cases of the `StepsizeLimiter` for hyperbolic PDEs:

1. An explicit Euler step will not be stable for high-order semidiscretisations in general. However, the `StepsizeLimiter` can still be used to enforce a CFL condition, guaranteeing stability for high-order time integrators. In general, this CFL condition will depend on both the semidiscretisation and the time integrator.
2. An explicit Euler step can have "secondary stability properties", e.g. the preservation of non-negativity of a density. In this case, if the stable time step for the Euler method is `dtFE`, an explicit SSP integrator can use time steps of size `ssp_coefficient(alg) * dtFE`.

I don't see how both use cases can be summed up in one elegant framework. Additionally, the user might want to reduce the time steps sizes below the stability limit. Thus, using the current `StepsizeLimiter` callback may be fine. However, `ssp_coefficient` should be documented somewhere.

### Limiters
In the second use case described above, the "secondary stability properties" can be rather weak. As an example, in a discontinuous Galerkin method, the numerical solution can be approximated as a polynomial in each cell. If the solutions represents a density, it should be non-negative. The "secondary stability properties" of the explicit Euler step may include the preservation of non-negativity of the *mean value of the numerical solution*, not of the entire solution. In this case, an additional limiting procedure can be used, scaling the polynomial towards its mean value. This kind of limiter should be applied after each stage of the method, since negative densities will probably result in a blow-up / crash of the numerical solution.

I don't have a minimal example now. However, it would be nice to specify a `stage_limiter!(t, u_new, du_old)` that performs this additional limiting. Here, `t` can be the new time, `u_new` the new solution, and `du_old` the time derivative of the old solution, i.e. `u_new = u_old + dt * du_old`. However, this may have lower priority until semidiscretisations using these limiters have been implemented.

**Comment by ChrisRackauckas** [comment]
> However, it would be nice to specify a stage_limiter!(t, u_new, du_old) that performs this additional limiting. Here, t can be the new time, u_new the new solution, and du_old the time derivative of the old solution, i.e. u_new = u_old + dt * du_old

It sounds like the SSP integrators should take in a function `stage_limiter!(t, u_new, du_old)` as an optional argument, and default to `stage_limiter!(t, u_new, du_old) = nothing`. Then the SSP methods can implement this per step. I assume this only makes sense on the SSP methods? If so, the SSP methods can just add this call between each step.

Note we should probably do `stage_limiter!(u,t,du)` to match what's normal for inplace syntax.

**Comment by ranocha** [comment]
I've added the limiters in #170. The interface is now `limiter!(u, f, t)`, where `u` is the new solution value (updated inplace), `f` the time derivative function (semidiscretisation for PDEs), and `t` the time. That should be sufficient for the use cases I'm aware of.
There is a `stage_limiter!`that is applied after every explicit Euler stage of the algorithm and a `step_limiter!`that is applied at the end of the step.

**Comment by ChrisRackauckas** [comment]
Is this issue complete?

**Comment by ranocha** [comment]
I think so, yes. While there are still many SSP methods, several explicit SSPRK are implemented.

**Comment by ranocha** [comment]
I've added `SSPRK54` (with numerical `Float64` coefficients) in #174.

**Comment by ChrisRackauckas** [comment]
Alright cool. We can address the others more specifically then. Thanks!
