### ISSUE TITLE
Optimize QNDF and QBDF

### ISSUE THREAD

**Issue by sipah00** [JuliaDiffEq/OrdinaryDiffEq.jl#491]
The following benchmarks are done on [problem](http://nbviewer.jupyter.org/github/JuliaDiffEq/DiffEqBenchmarks.jl/blob/master/StiffODE/Hires.ipynb)

#### At High Tolerances
```
abstols = 1 . /10 .^ (5:8)
reltols = 1 ./ 10 .^ (1:4);
setups = [Dict(:alg=>Rosenbrock23()),
		  Dict(:alg=>QBDF()),
		  Dict(:alg=>QNDF()),
		  Dict(:alg=>QBDF2()),
		  Dict(:alg=>QNDF2()),
                  Dict(:alg=>Rodas3()),
                  Dict(:alg=>TRBDF2()),
                  Dict(:alg=>CVODE_BDF())]
wp = WorkPrecisionSet(prob,abstols,reltols,setups;save_everystep=false,appxsol=test_sol,maxiters=Int(1e5))
plot(wp)
```
![plot1](https://user-images.githubusercontent.com/23627932/44421434-1b864400-a59e-11e8-82ee-cd1596ebc422.png)

```
wp = WorkPrecisionSet(prob,abstols,reltols,setups;dense = false,verbose=false,
                      appxsol=test_sol,maxiters=Int(1e5),error_estimate=:l2)
plot(wp)
```
![plot2](https://user-images.githubusercontent.com/23627932/44421675-e29a9f00-a59e-11e8-9599-bfdf1845bae1.png)
```
wp = WorkPrecisionSet(prob,abstols,reltols,setups;
                      appxsol=test_sol,maxiters=Int(1e5),error_estimate=:L2)
plot(wp)
```
![plot3](https://user-images.githubusercontent.com/23627932/44421689-ecbc9d80-a59e-11e8-939d-f5f241ba934d.png)

We can see that `QNDF` and `QBDF` are not performing good.

**Comment by ChrisRackauckas** [comment]
What lines do the profiles say matters?

What I notice without profiling is that this part right here:

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/bdf_perform_step.jl#L871-L879

`zero(u)` allocates, so this is allocating a ton. You'll want to call `fill!` with a zero of the element type on each index, not create `zero(u)`. 

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/bdf_perform_step.jl#L867

`udiff` is always vectors, so that can be pointer swapping. 

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/bdf_perform_step.jl#L850-L858

More allocating.

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/bdf_perform_step.jl#L796
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/bdf_perform_step.jl#L791

More allocating.

https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/perform_step/bdf_perform_step.jl#L773

That should be a `mul!` call. 

That's what immediately stands out to me and is a starting point.

**Comment by sipah00** [comment]
Actually, I thought out of place version would not be used for system of ODEs.

**Comment by sipah00** [comment]
ohh got it.

**Comment by YingboMa** [comment]
#602
