### ISSUE TITLE
Floating point error reduction in error estimates

### ISSUE THREAD

**Issue by ChrisRackauckas** [JuliaDiffEq/OrdinaryDiffEq.jl#93]
```julia
atmp[i] = (utilde[i]-u[i])/(atol+max(abs(uprev[i]),abs(u[i]))*rtol)
```

That is actually higher on the level of cancellation that it can be. What we could do is define `btildei = bi -
 a7i` (and comment out the `bi` in the tableaus for future reference but they are unnecessary to keep) and then redefine

```julia
utilde[i] = dt*(btilde1*k1[i] + btilde2*k2[i] + btilde3*k3[i] + btilde4*k4[i] + btilde5*k5[i] + btilde6*k6[i] + btilde7*k7[i])
```

with

```julia
atmp[i] = utilde[i]/(atol+max(abs(uprev[i]),abs(u[i]))*rtol)
```

By getting rid of the `uprev[i]` cancelation between `utilde` and `u` we decrease the largest value, and thus more digits will be floating point representable.

**Comment by devmotion** [comment]
Using `Rodas4` I just encountered the problem with summation order you already mentioned in https://github.com/JuliaDiffEq/DelayDiffEq.jl/pull/22#issuecomment-319577582. This might cause unnoticed problems in other algorithms as well.

I wanted to update the in-place and not in-place methods of this algorithm to `@muladd` and dot calls, and suddenly the tests did not pass anymore. So I also had a look at the current implementation in https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/rosenbrock_integrators.jl#L920 and https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/rosenbrock_integrators.jl#L1028, and used the following snippet with three identical problems to compare the not in-place implementation (with scalars and vectors) and the in-place implementation:
```julia
using OrdinaryDiffEq, DiffEqProblemLibrary, DiffEqDevTools

dts = 1.//2.^(8:-1:4)

# Not in-place

prob = prob_ode_linear

sim = test_convergence(dts,prob,Rodas42(),dense_errors=true)
@show abs(sim.𝒪est[:final]-4.3)

prob = ODEProblem(DiffEqProblemLibrary.linear, [1/2], (0.0, 1.0))

sim = test_convergence(dts,prob,Rodas42(),dense_errors=true)
@show abs(sim.𝒪est[:final]-4.3)

# In-place

prob = ODEProblem(DiffEqProblemLibrary.f_2dlinear, [1/2], (0.0, 1.0))

sim = test_convergence(dts,prob,Rodas42(),dense_errors=true)
@show abs(sim.𝒪est[:final]-4.3)
```
Then with the current implementation, I get
```julia
abs(sim.𝒪est[:final] - 4.3) = 0.026497492486114105
abs(sim.𝒪est[:final] - 4.3) = 0.026497492486114105
abs(sim.𝒪est[:final] - 4.3) = 0.06897849553189594
```
which means the in-place implementation yields quite different results. The difference is due to missing brackets in the in-place implementation in lines
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/rosenbrock_integrators.jl#L1125
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/rosenbrock_integrators.jl#L1143
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/rosenbrock_integrators.jl#L1161
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/rosenbrock_integrators.jl#L1179
compared to not in-place code in lines
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/rosenbrock_integrators.jl#L974
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/rosenbrock_integrators.jl#L982
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/rosenbrock_integrators.jl#L990
https://github.com/JuliaDiffEq/OrdinaryDiffEq.jl/blob/master/src/integrators/rosenbrock_integrators.jl#L998
since after adding those brackets I obtain
```julia
abs(sim.𝒪est[:final] - 4.3) = 0.026497492486114105
abs(sim.𝒪est[:final] - 4.3) = 0.026497492486114105
abs(sim.𝒪est[:final] - 4.3) = 0.026497492486114105
```
i.e. identical results for all implementations. As expected, we get the same results by replacing loops with broadcast expressions.

However, I was completely puzzled when I got
```julia
abs(sim.𝒪est[:final] - 4.3) = Inf
abs(sim.𝒪est[:final] - 4.3) = Inf
```
for the not in-place function, just by adding `@muladd` to the function head. And again this is caused by the order of summation - in particular, the problem is that `muladd` reorders the summation-multiplication complex in such a way that the leftmost multiplication is executed at last, contrary to the otherwise left-to-right evaluation. I would suggest changing `@muladd` in such a way that at least the order of evaluation of the summation-multiplication complexes is left unchanged (i.e. the implementation should be reversed) and summands with `n` factors are split in two groups of the first `n-1` factors and the last factor (i.e. contrary to the current implementation; this should leave the evaluation order unchanged also inside of each summand). However, I'm not sure whether it would be best to evaluate the sum of all not-multiplication summands first (as currently done) or last.

Of course, this might be an extremely sensitive example, but it shows that even minor changes can lead to quite different results and there might be more algorithms with different results for not in-place and in-place functions.

BTW, I discovered another strange thing while debugging the examples above:
```julia
julia> muladd(-1451.2128, 0.001048780568616764, 1.0)
-0.522003785567926
julia> muladd.(-1451.2128, 0.001048780568616764, 1.0)
-0.5220037855679261
julia> muladd.(-1451.2128, [0.001048780568616764], [1.0])[1]
-0.522003785567926
julia> muladd.([-1451.2128], [0.001048780568616764], [1.0])[1]
-0.522003785567926
```
As we have to deal with both scalars and a mix of scalars and vectors in the not in-place algorithms, we would like to use `muladd.` whenever possible - but it seems `muladd.` leads to slightly different results when used with scalars?!
The example above is a reduced version of:
```julia
julia> @muladd (1.0745275442591873 + (-0.000407421875)*0.0) + (-1451.2128)*0.001048780568616764
-0.44747624130873875
julia> @. 1.0745275442591873 + (-0.000407421875)*0.0 + (-1451.2128)*0.001048780568616764
-0.44747624130873875
julia> @muladd @. 1.0745275442591873 + (-0.000407421875)*0.0 + (-1451.2128)*0.001048780568616764
-0.44747624130873886
```

**Comment by ChrisRackauckas** [comment]
I don't think adding the brackets is necessary more correct: they should probably be removed from the not-in-place version to let the optimizer choose how to do it. If anything, the ordering should be by the size of the constants, smallest to largest. Whatever we do though, it would be good to at least try to have the ordering in not-in-place and in-place be the same.

Sounds like `@muladd` reverses that though, so it would be good to fix. Open an issue on MuladdMacro.jl?

>As we have to deal with both scalars and a mix of scalars and vectors in the not in-place algorithms, we would like to use muladd. whenever possible - but it seems muladd. leads to slightly different results when used with scalars?!

Apparently that's different on v0.7 according to the Slack. Beyond our control and has to do with optimizers. The issue there is that the broadcasted version uses `fma` while the non-broadcasted version is not due to a cost analysis. We'd have to force `fma` there if we want it to always be the same, but `muladd` is more efficient, especially when hardware `fma` doesn't exist.

But the `abs(sim.𝒪est[:final] - 4.3) = Inf`. That's a bug. We should get `@muladd` working on that. Those didn't have muladd because for some reason sprinkling it everywhere before didn't work. Maybe it will need to be done more precisely to find out what's causing it.

**Comment by ChrisRackauckas** [comment]
>more likely muladd is running in the interpreter, which just does the mul, then the add while the broadcast version is compiled

Keno said that could be the reason for the `muladd.` difference.

**Comment by devmotion** [comment]
> But the abs(sim.𝒪est[:final] - 4.3) = Inf. That's a bug. We should get @muladd working on that. Those didn't have muladd because for some reason sprinkling it everywhere before didn't work. Maybe it will need to be done more precisely to find out what's causing it.

https://github.com/JuliaDiffEq/MuladdMacro.jl/pull/4 fixes this problem, using broadcasts and `@muladd` without brackets I now obtain
```julia
abs(sim.𝒪est[:final] - 4.3) = 0.06897849553189594
abs(sim.𝒪est[:final] - 4.3) = 0.06897849553189594
abs(sim.𝒪est[:final] - 4.3) = 0.06897849553189594
```
i.e. the same result as for the in-place method without brackets before.

> I don't think adding the brackets is necessary more correct: they should probably be removed from the not-in-place version to let the optimizer choose how to do it.

With `muladd` the order of evaluation is always fixed. Without this PR it was a reversed right-to-left order, which seems both unexpected and undesired, now it is a fixed left-to-right order of evaluation. So it will be easier to sort the summands without any surprising reordering by `@muladd`.

**Comment by ChrisRackauckas** [comment]
I believe this is fixed everywhere. For others that were missed it can be more specific.
